# -*- coding: utf-8 -*-
{
    'name': "Petrol Station Management System",
    'version': 'PSIMS-1.0',
    'summary': """Manage Petrol Station Information System""",
    'description': """This Module Manage Petrol Station Information System""",
    'author': "Utshav Ghimire",
    'company': 'Sayapatri Technology',
    'website': "https://www.sayapatritech.com",
    'category': 'Accounting',
    'depends': ['base', 'sale', 'account', 'procurement','ab_access_control'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/res_partner.xml',
        'views/petrolstation_menu.xml',
        'views/token_management.xml',
        'views/vehicle_info.xml',
        'data/sequence.xml',
        'report/token_pdf.xml',
        'report/report_token.xml',
        'views/sales_agreement.xml',
        'views/account_invoice.xml',
        'views/sale_order.xml',
        'report/report_salesagreement.xml',
        'report/sales_agreement_report.xml',
        'report/report_token_receipt.xml',
        'report/token_receipt.xml',
        'views/token_sales_tree.xml',
        'views/token_sales.xml',
        'report/tax_invoice.xml',
        'report/invoice_template.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
